apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: morsaas-dev
  namespace: 101868473812
  labels:
    environment: test
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/startup-cpu-boost: 'true'
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/client-name: github-actions
        run.googleapis.com/client-version: GITHUB_SHA
        run.googleapis.com/startup-probe-timeout: '240s'
    spec:
      containerConcurrency: 80
      containers:
      - image: gcr.io/101868473812/morsaas-dev:latest
        env:
        - name: NODE_ENV
          value: production
        - name: REDIS_URL
          value: rediss://default:AbexAAIjcDE1M2Q4MWMxZTU5N2Q0MzEzYjQ0ZmM0NjIzZGUyYjQxMXAxMA@learning-goblin-47025.upstash.io:6379
        - name: REACT_APP_AVAILABLE_MODELS
          value: mistralai/mistral-small-3.1-24b-instruct:free|Mistral Small 3.1 24B,deepseek/deepseek-r1-zero:free|Deepseek R1 Zero,meta-llama/llama-3.3-70b-instruct:free|Llama 3.3 70B
        - name: SECONDARY_ENDPOINT_URL
          value: https://openrouter.ai/api/v1/chat/completions
        - name: SECONDARY_ENDPOINT_TOKEN
          valueFrom:
            secretKeyRef:
              name: openai-api-key
              key: latest
        - name: SECONDARY_ENDPOINT_MODEL
          value: meta-llama/llama-3.3-70b-instruct:free
        - name: CONSUMER_API_URL
          value: https://consumer-node-1081887913409.us-west1.run.app
        - name: USE_FALLBACK_AS_PRIMARY
          value: "false"
        - name: OPENROUTER_HTTP_REFERER
          value: https://morsaas-dev.run.app
        - name: OPENROUTER_APP_TITLE
          value: MorSaaS-Dev
        - name: OPENROUTER_APP_VERSION
          value: 1.0.0-dev
