apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/urls: '["https://morsaas-101868473812.us-west1.run.app"]'
  labels:
    cloud.googleapis.com/location: us-west1
  name: morsaas
  namespace: '101868473812'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 514.0.0
        run.googleapis.com/cpu-throttling: 'false'
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: lcozpjkttm
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: NODE_ENV
          value: production
        - name: REDIS_URL
          value: redis://default:AbexAAIjcDE1M2Q4MWMxZTU5N2Q0MzEzYjQ0ZmM0NjIzZGUyYjQxMXAxMA@learning-goblin-47025.upstash.io:6379
        - name: SECONDARY_ENDPOINT_URL
          value: https://api.openai.com/v1/chat/completions
        - name: SECONDARY_ENDPOINT_TOKEN
          valueFrom:
            secretKeyRef:
              key: openai-api-key
              name: morsaas-secrets
        - name: CONSUMER_API_URL
          value: https://consumer-node-1081887913409.us-west1.run.app
        image: gcr.io/graphical-bus-433219-g5/morsaas:6fc5026623ee01df79f4f92b35eb8950ae8a621b
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: '1'
            memory: 2Gi
        startupProbe:
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 60
          tcpSocket:
            port: 8080
          timeoutSeconds: 30
      serviceAccountName: 101868473812-compute@developer.gserviceaccount.com
      timeoutSeconds: 600
  traffic:
  - latestRevision: true
    percent: 100
