apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: morsaas
spec:
  template:
    spec:
      containers:
      - image: gcr.io/graphical-bus-433219-g5/morsaas:6fc5026623ee01df79f4f92b35eb8950ae8a621b
        env:
        - name: NODE_ENV
          value: production
        - name: REDIS_URL
          value: rediss://default:AbexAAIjcDE1M2Q4MWMxZTU5N2Q0MzEzYjQ0ZmM0NjIzZGUyYjQxMXAxMA@learning-goblin-47025.upstash.io:6379
        resources:
          limits:
            cpu: '1'
            memory: 2Gi
        startupProbe:
          # Maximum allowed values for startup probe
          initialDelaySeconds: 240
          periodSeconds: 240
          timeoutSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 8080
      timeoutSeconds: 600 