apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: morsaas
  namespace: default
  labels:
    environment: ENVIRONMENT_NAME
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/startup-cpu-boost: 'true'
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/client-name: github-actions
        run.googleapis.com/client-version: GITHUB_SHA
        run.googleapis.com/startup-probe-timeout: '240s'
    spec:
      containerConcurrency: 80
      containers:
      - image: gcr.io/PROJECT_ID/morsaas:COMMIT_SHA
        env:
        - name: NODE_ENV
          value: production
        - name: REDIS_URL
          value: YOUR_REDIS_URL
        - name: REACT_APP_AVAILABLE_MODELS
          value: REACT_APP_AVAILABLE_MODELS_VALUE
        - name: SECONDARY_ENDPOINT_URL
          value: SECONDARY_ENDPOINT_URL_VALUE
        - name: SECONDARY_ENDPOINT_TOKEN_KEY
          value: SECONDARY_ENDPOINT_TOKEN_KEY
        - name: SECONDARY_ENDPOINT_MODEL
          value: SECONDARY_ENDPOINT_MODEL_VALUE
        - name: CONSUMER_API_URL
          value: CONSUMER_API_URL_VALUE
        - name: USE_FALLBACK_AS_PRIMARY
          value: "USE_FALLBACK_AS_PRIMARY_VALUE"
        - name: OPENROUTER_HTTP_REFERER
          value: OPENROUTER_HTTP_REFERER_VALUE
        - name: OPENROUTER_APP_TITLE
          value: OPENROUTER_APP_TITLE_VALUE
        - name: OPENROUTER_APP_VERSION
          value: OPENROUTER_APP_VERSION_VALUE
